[font]
normal = { family = "DinaRemasterII Nerd Font", style = "Regular" }
size = 21
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }
# size = 18
# normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
# size = 18

[window]
option_as_alt = "Both"

# https://gist.github.com/sainnhe/ad5cbc4f05c4ced83f80e54d9a75d22f
# Colors (gruvbox_material_medium_dark)
[colors.primary]
background = '0x282828'
foreground = '0xd4be98'

[colors.normal]
# black   = '0x3c3836'
black   = '0xa89984'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
# chalk uses this but isn't smart enough to prevent dark on dark
# black   = '0x3c3836'
black   = '0xa89984'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[keyboard]
bindings = [
  # Disable macOS binding for new tab-- tabs do not interoperate with aerospace
  { key = "T", mods = "Command", action = "ReceiveChar" }
]

[scrolling]
# Default=10000 -- 100000 is is the max alacritty supports
history = 100000
